### ISSUE TITLE
Trigger when tabs are changed

### ISSUE THREAD

**Issue by modulbuero** [proteusthemes/tabs-widget-for-page-builder#10]
Hey guys,

we're running jQuery MatchHeight inside your Tabs widget. For the first tab, everything works fine. The other tabs don't work, because MatchHeight doesn't know they're present until shown. What we'd need is a trigger for when tabs are changed to run MatchHeight again. I guess there already are triggers in your main.min.js, but i can't read this file. Could you tell me which triggers are available or provide an unminifed version of main.js? 

Thanks a lot,
Christian

**Comment by modulbuero** [comment]
Found a workaround, that's not to clever, but does work:

```
jQuery(function() {
	jQuery('.pt-tabs .pt-tabs__navigation .nav-item a').on('click', function(e) {
		window.setTimeout(function() {
			jQuery.fn.matchHeight._update();
		}, 250);
	});
});
```

A real trigger would still be nicer, though.

**Comment by capuderg** [comment]
Hi,

the tabs are made with Bootstrap, so a Bootstrap "show" event can be used, to run the update of your code. More info here: http://v4-alpha.getbootstrap.com/components/navs/#events

Use the proper selector in order to only target our tabs...

Take care!

**Comment by modulbuero** [comment]
Worked perfectly. Thanks, man!

**Comment by capuderg** [comment]
no problem :)

Have a nice day!
