### ISSUE TITLE
Make it compatible with Bootstrap v3

### ISSUE THREAD

**Issue by capuderg** [proteusthemes/tabs-widget-for-page-builder#3]
Should we do that? Since the majority of themes use bootstrap v3 and include it with the theme...

**Comment by primozcigler** [comment]
I am not 100% sure what the question is really about and what it affects. Please elaborate @capuderg

**Comment by capuderg** [comment]
The tabs HTML and CSS is slightly different in bootstrap v4 then it is in v3.

This has nothing to do with our Beauty theme... maybe it would be good for the plugin, to have a filter, where you could switch from existing bootstrap version (v4) to v3, so that it would be compatible with other themes using bootstrap v3.

I opened this issue just so I don't forget about this. I have to still check what the differences between v4 and v3 are...

**Comment by primozcigler** [comment]
In this case I would encourage pull requests from the people who will actually need this. If someone asks for this feature in wordpress.org ask them to create a pull request in this repo.

**Comment by capuderg** [comment]
There were no more issues reported on the matter, so I'm closing the ticket for now...

**Comment by capuderg** [comment]
New reported issues with themes using bootstrap v3:
https://wordpress.org/support/topic/first-tab-always-stays-active?replies=9#post-8511256
https://wordpress.org/support/topic/pagebuilder-slider-widget-not-working-properly?replies=4

If I'll have some free time, I'm going to implement this, but it's definitely not a priority...

**Comment by capuderg** [comment]
The issue seams to be that themes include other versions of Bootstrap JS for tabs:
- https://wordpress.org/themes/ascent/ - v3.x
- https://wordpress.org/themes/customizr/ - v2.x

Both of these versions have different HTML for tabs and that's why it "breaks". The difference is in the `active` class, in v4 it's on the `a` tag, but in v3, it's on the `li` tag (so the first tab always stays active).
